### PR TITLE
Travis update

### PR DESCRIPTION
**Pull request by luan-cestari**

### CODE REVIEW

**Comment by jewzaam** [comment]
We could move things to etc dir but there's no need for travis and/or coveralls in this repo.  Everything in here is built by the individual repo.

**Comment by luan-cestari** [comment]
For me that is fine. So even the whole repository is pointless? The only point that I enable travis was to it monitor if we forget to update a git submodule (and other related issues).

**Comment by jewzaam** [comment]
There are two purposes to this module:
1. ability to publish all module's sonar metrics at one time (using submodules)
2. store any one-off documents that don't belong to a specific repo and are not part of the gitbook documentation

**Comment by luan-cestari** [comment]
Well, if you see that travis will not help with CI for this repo (like the submodule issue or other things), lets close this PR (I don't see any problem if the changes are pointless)

**Comment by jewzaam** [comment]
Maybe a benefit for using travis would be to catch issues where a change in one module breaks a dependent module.  But, this module will not be able to do all the things that other modules do.  Instead, it would be:
1. pre build, update submodules (see update.sh)
2. build

And that's it.  Let unit tests run, but only so we can report a failure.  And no publishing artifacts to sonatype.  I'd say no coveralls as well, but there isn't a real impact if we did include it.  It would just be an overall test coverage number, which might be nice to see.

What do you think?

**Comment by luan-cestari** [comment]
This seems pretty good idea (specially the overall test coverage, that can be helpful number to we see ) . So, as we are going to release Ana today and this PR  would need changes to archive that, I would suggest to we open an issue that address the requirements that you described. Do you agree?

**Comment by jewzaam** [comment]
I'm interested in seeing this done sooner rather than later.  I can take knocking out a new PR for that work instead of creating an issue.  Then this PR can simply be closed, right?

**Comment by jewzaam** [comment]
See https://github.com/lightblue-platform/lightblue/pull/18

**Pull request closed without merging**
